when:
  event: push

steps:
  - name: flake check
    image: nixos/nix
    commands:
      - |
        export NIX_CONFIG="
          extra-experimental-features = nix-command flakes
          http-connections = 128
          max-substitution-jobs = 128
        "
      - nix flake check --show-trace
# TODO: figure out how to put cachix into this
